import { createSlice } from "@reduxjs/toolkit";

// Initial state
const initialState = { value: 0 };

// Create slice
const useCounter = createSlice({
  name: "useCounter",
  initialState,
  reducers: {
    // Define action to increment
    increment: (state) => {
      state.value += 1;
    },
    // Define action to decrement
    decrement: (state) => {
      state.value -= 1;
    },
    // Define action to reset the counter
    reset: (state) => {
      state.value = 0;
    },
    // Define action to increment by a specific amount
    incrementByAmount: (state, action) => {
      state.value += action.payload;
    },
  },
});

// Export actions generated by createSlice
export const { increment, decrement, reset, incrementByAmount } =
  useCounter.actions;

// Export the reducer to be included in the store
export default useCounter.reducer;
