import { createSlice } from "@reduxjs/toolkit";
import Cookie from "js-cookie";

// Initial state
const initialState = { token: "" };

// Create slice
const useAuth = createSlice({
  name: "useAuth",
  initialState,
  reducers: {
    login: (state) => {
      state.token = "xyz";
      Cookie.set("token", "xyz");
    },
    logout: (state) => {
      state.token = "";
      Cookie.remove("token");
    },
    getToken: (state) => {
      state.token = Cookie.get("token") || "";
    },
  },
});

// Export actions generated by createSlice
export const { login, getToken, logout } = useAuth.actions;

// Export the reducer to be included in the store
export default useAuth.reducer;
